import React from 'react';
import {Container, Row, Col} from 'react-bootstrap';

const About = () => {
  return (
    <>
        <Container style={{marginTop:'50px'}}>
            <h1>Qui sommes-nous ?</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia voluptate beatae officiis quasi quisquam tenetur, non nesciunt eaque praesentium delectus quia ducimus culpa animi aliquam repellendus, excepturi eveniet error ipsa distinctio cumque voluptatem! Perferendis doloribus iure animi exercitationem fuga voluptatem eaque. Molestiae rem reiciendis omnis laborum ratione, hic doloribus possimus perspiciatis, ex veniam tenetur cupiditate molestias dolore vel, fuga dolorem iure iusto a labore dignissimos nostrum. Eligendi nisi dolore expedita molestias quaerat debitis maiores eos possimus, esse consequatur repudiandae impedit dolor itaque neque suscipit ut asperiores fugiat inventore labore ipsa odit mollitia numquam harum accusantium? Esse voluptatibus nam sunt amet. Assumenda, explicabo obcaecati omnis modi, at iusto eos optio odio non pariatur quis ea beatae maxime deserunt placeat veniam in ipsum voluptate molestiae aspernatur velit. Maiores perferendis quaerat iste esse aspernatur porro, cum nobis doloribus unde, tempora in ipsa nesciunt iure non vero quis, fugit dolore ad voluptatum odio velit quidem. Vel rerum magnam ratione ad unde quam adipisci voluptates iste vero blanditiis! Aliquid eos, itaque facere voluptatum consequuntur consectetur ipsum tenetur cumque beatae neque aperiam ullam enim fuga illo consequatur ut vitae, perspiciatis quis? Nulla culpa dolores soluta quam dolorem amet vel accusamus, repudiandae iusto, praesentium, reprehenderit voluptates distinctio.</p>
            <h1>Notre spécialité</h1>
            <Row>
                <Col  md={6}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe alias enim voluptate! Ipsum dicta magni impedit sed, odio temporibus fuga quo delectus sequi! Tenetur quia recusandae sed molestias nam obcaecati, soluta aspernatur sequi est necessitatibus aut veritatis vel exercitationem nulla blanditiis? Omnis voluptates autem perspiciatis, quam delectus dicta atque voluptatum reiciendis facere necessitatibus. Pariatur laborum blanditiis dolor accusamus sint vitae, excepturi cupiditate id esse nulla doloremque, facilis quasi maiores deserunt quo quibusdam beatae ipsum nesciunt debitis asperiores illo! Veniam, neque architecto inventore animi esse dolores, voluptatum, dolore placeat perspiciatis incidunt deserunt nihil nemo dolorum. Provident asperiores reiciendis odio eum doloribus voluptas tenetur, delectus aut nisi excepturi quis quisquam quibusdam quia assumenda ex illo iure? Labore ducimus, esse dolores beatae, at rem ut optio vel quas voluptas debitis nulla perferendis recusandae tempora, omnis dolorum maxime animi. Eius sed illo dolorem explicabo voluptas corporis iure natus esse omnis, accusamus neque ipsum error hic porro dolor obcaecati! Debitis, voluptate! Similique placeat dicta dolorum possimus recusandae corporis eum assumenda, veniam eligendi doloribus facere voluptates, fugiat, aperiam reiciendis iure. Ipsum sequi ipsam sed ea autem maxime provident distinctio. Eaque pariatur eum, exercitationem at quis quae quo neque nesciunt blanditiis? Nemo ratione expedita molestiae facere tempore.</p>
                </Col>
                <Col md={6}>
                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil libero cum eveniet sapiente voluptatum a magni doloremque voluptatem! Deleniti cum consequatur tenetur velit impedit reiciendis illum ipsa provident itaque corrupti. Illo impedit atque dolores, illum, iure molestiae sit obcaecati facere molestias tenetur assumenda omnis numquam consequatur aliquam, soluta harum libero id unde dolor vel. Recusandae asperiores voluptatibus nemo beatae quasi quia commodi culpa, saepe dolore aliquam, magni obcaecati soluta, atque ullam pariatur rem explicabo illo facere aperiam! Esse dolor dolorum nisi quam sit voluptates quia a officiis explicabo hic incidunt quidem eius eos fugit ipsam, consequatur quibusdam, libero, illo deleniti distinctio reiciendis nostrum iste numquam maxime. Nihil asperiores atque consequatur suscipit exercitationem sunt natus vel dolorum dolore, voluptatum provident, officia cupiditate? Praesentium expedita ipsam libero rem odio in iusto nostrum possimus deserunt omnis, non dolore fugiat accusantium sequi facilis inventore ab voluptatibus rerum sed magni voluptatum minima. Ratione animi fuga in dignissimos. Non modi ratione nulla porro. Id quam nobis vitae sint eius voluptatem tempore suscipit incidunt quisquam, labore quasi expedita consequuntur perferendis iusto nulla cum modi ea tenetur sequi quos enim esse! Ullam consequatur corrupti fugit atque voluptatibus et, voluptatem nihil, iure consequuntur nam officia a, illo facere nulla.</p>
                </Col>
            </Row>
            <Row>
                <h1>Le chef</h1>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In exercitationem quaerat nesciunt. Ea amet nemo, et odio vitae, magni quos recusandae provident nobis a doloremque velit nostrum enim eaque omnis, ex porro dolor. Debitis id culpa temporibus maiores sit, consequatur sapiente aut totam aperiam nesciunt laudantium provident illo quidem eaque saepe, corporis quaerat fugiat ad fugit non a officiis cum nisi. Quos velit minima necessitatibus eius nesciunt sunt totam impedit eum repudiandae, ex soluta mollitia aliquam dolorum qui a, maxime, saepe quam! Vitae eum esse ullam provident. Neque labore, maxime possimus molestias iste quisquam similique obcaecati sequi qui, laborum dolores!</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In exercitationem quaerat nesciunt. Ea amet nemo, et odio vitae, magni quos recusandae provident nobis a doloremque velit nostrum enim eaque omnis, ex porro dolor. Debitis id culpa temporibus maiores sit, consequatur sapiente aut totam aperiam nesciunt laudantium provident illo quidem eaque saepe, corporis quaerat fugiat ad fugit non a officiis cum nisi. Quos velit minima necessitatibus eius nesciunt sunt totam impedit eum repudiandae, ex soluta mollitia aliquam dolorum qui a, maxime, saepe quam! Vitae eum esse ullam provident. Neque labore, maxime possimus molestias iste quisquam similique obcaecati sequi qui, laborum dolores!</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In exercitationem quaerat nesciunt. Ea amet nemo, et odio vitae, magni quos recusandae provident nobis a doloremque velit nostrum enim eaque omnis, ex porro dolor. Debitis id culpa temporibus maiores sit, consequatur sapiente aut totam aperiam nesciunt laudantium provident illo quidem eaque saepe, corporis quaerat fugiat ad fugit non a officiis cum nisi. Quos velit minima necessitatibus eius nesciunt sunt totam impedit eum repudiandae, ex soluta mollitia aliquam dolorum qui a, maxime, saepe quam! Vitae eum esse ullam provident. Neque labore, maxime possimus molestias iste quisquam similique obcaecati sequi qui, laborum dolores!</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In exercitationem quaerat nesciunt. Ea amet nemo, et odio vitae, magni quos recusandae provident nobis a doloremque velit nostrum enim eaque omnis, ex porro dolor. Debitis id culpa temporibus maiores sit, consequatur sapiente aut totam aperiam nesciunt laudantium provident illo quidem eaque saepe, corporis quaerat fugiat ad fugit non a officiis cum nisi. Quos velit minima necessitatibus eius nesciunt sunt totam impedit eum repudiandae, ex soluta mollitia aliquam dolorum qui a, maxime, saepe quam! Vitae eum esse ullam provident. Neque labore, maxime possimus molestias iste quisquam similique obcaecati sequi qui, laborum dolores!</p>
                </Col>
            </Row>
        </Container>
    </>
  );
};

export default About;